"""empty message

Revision ID: b2a9c60941f8
Revises: 496c8d9e2719
Create Date: 2023-09-29 16:39:56.426731

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b2a9c60941f8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Documents', sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
                                 sa.Column('psth', sa.String(100), nullable=False),
                                 sa.Column('date', sa.Date(), nullable=False))
    op.create_table('Documents_text', sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
                                      sa.Column('id_doc', sa.Integer(), sa.ForeignKey('Documents.id', ondelete='CASCADE')),
                                      sa.Column('text', sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
